### ISSUE TITLE
How can I use your porter stemmer?

### ISSUE THREAD

**Issue by Yaoyaolingbro** [amallia/Porter2#6]
You've code neatly. However, I want use your code to do a mini-search engine. So what should I do? ( I can't read CMakeList.txt correctly) Thanks for your tutorial answer.

**Comment by JMMackenzie** [comment]
Hi there,

Thanks for your comment - sorry I missed it until now. Could you describe your problem in more detail? What is your use case?

**Comment by Yaoyaolingbro** [comment]
Thank you for your reply! I've solve it by static link (libPorter.o) after cmake to solve this problem. However, I have to say that there is a tiny mistake that the code in your readme can't work hhh!

**Comment by JMMackenzie** [comment]
Haha yes, someone else fixed that recently. Thanks for letting us know, I will close this off now.
